server:
  port: 8443

spring:
  datasource:
    # 每次运行时初始化数据库，如不需要可以注释掉
#    initialization-mode: always
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.99.100:3306/white_jotter?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wj
    username: postgres
    password: password
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          # Meant to hide HHH000424: Disabling contextual LOB creation as createClob() method threw error
          use_jdbc_metadata_defaults: false
